import streamlit as st
import torch
import torch.nn as nn
from torchvision import models, transforms, datasets
from PIL import Image
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
import numpy as np
import cv2
from src.segmentation import segment_lung
import base64
import streamlit.components.v1 as components
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from datetime import datetime
import tempfile
import io
from pathlib import Path


st.set_page_config(layout="wide")


@st.cache_data(show_spinner=False)
def get_base64_image(image_path):
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode()


def build_slider_keyframes(image_count):
    if image_count <= 1:
        return "0% { transform: translateX(0%); } 100% { transform: translateX(0%); }"

    keyframes = []
    step = 100 / image_count
    hold = step * 0.82

    for index in range(image_count):
        position = -(index * step)
        start = index * step
        end = min(start + hold, 100)

        keyframes.append(f"{start:.2f}% {{ transform: translateX({position:.2f}%); }}")
        keyframes.append(f"{end:.2f}% {{ transform: translateX({position:.2f}%); }}")

    keyframes.append("100% { transform: translateX(0%); }")
    return "\n".join(keyframes)


def is_likely_ct_scan(image):
    img_np = np.array(image)

    # Check if image is mostly grayscale
    if len(img_np.shape) == 3:
        r = img_np[:, :, 0]
        g = img_np[:, :, 1]
        b = img_np[:, :, 2]

        color_difference = np.mean(np.abs(r - g)) + np.mean(np.abs(g - b)) + np.mean(np.abs(r - b))

        if color_difference > 25:
            return False

    # Check brightness/contrast range
    gray = cv2.cvtColor(img_np, cv2.COLOR_RGB2GRAY)
    contrast = gray.std()

    if contrast < 10:
        return False

    return True


def create_pdf_report(prediction, confidence_score, confidence_category, segmentation_img, heatmap_img):
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf_path = temp_file.name

    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    # Header
    
    c.setFillColorRGB(0.0, 0.35, 0.65)
    c.rect(0, height - 95, width, 95, fill=1)

    # Header Text
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(40, height - 42, "AI Diagnostic Center")

    c.setFont("Helvetica", 12)
    c.drawString(42, height - 68, "Educational Lung Cancer Screening Report")

    # Reset text color
    c.setFillColorRGB(0, 0, 0)
    c.drawString(40, height - 85, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Main Results
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, height - 120, "Prediction Result")

    c.setFont("Helvetica", 12)
    c.drawString(60, height - 145, f"Prediction: {prediction}")
    c.drawString(60, height - 165, f"Confidence Score: {confidence_score:.2f}%")
    c.drawString(60, height - 185, f"Confidence Category: {confidence_category}")

    # Images
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, height - 225, "AI Findings")

    seg_pil = Image.fromarray(segmentation_img)
    heat_pil = Image.fromarray(heatmap_img)

    seg_buffer = io.BytesIO()
    heat_buffer = io.BytesIO()

    seg_pil.save(seg_buffer, format="PNG")
    heat_pil.save(heat_buffer, format="PNG")

    seg_buffer.seek(0)
    heat_buffer.seek(0)

    c.drawImage(ImageReader(seg_buffer), 40, height - 430, width=240, height=160)
    c.drawImage(ImageReader(heat_buffer), 310, height - 430, width=240, height=160)

    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, height - 470, "Recommendation")

    c.setFont("Helvetica", 11)

    if prediction == "cancer":
        c.drawString(60, height - 495, "Please consult a qualified doctor for further clinical evaluation.")
    else:
        c.drawString(60, height - 495, "No strong cancer pattern detected. Continue regular health checkups.")

    # Disclaimer
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, height - 540, "Medical Disclaimer")

    c.setFont("Helvetica", 10)
    c.drawString(60, height - 560, "This report is AI-generated for educational support only.")
    c.drawString(60, height - 575, "It must not be used as a final medical diagnosis.")

    # Footer
    c.setFont("Helvetica", 9)
    c.drawString(40, 30, "Generated by Lung Cancer Detection System")

    c.save()
    return pdf_path


st.title("Lung Cancer Detection System")

hero_images = [
    "images/hero1.jpg",
    "images/hero2.jpg",
    "images/hero3.jpg",
    "images/hero4.jpg",
    "images/hero5.jpg",
    "images/hero6.jpg",
]

hero_images = [img for img in hero_images if Path(img).exists()]

if hero_images:
    encoded_images = [get_base64_image(img) for img in hero_images]
    slider_keyframes = build_slider_keyframes(len(encoded_images))

    slider_html = f"""
<div style="width:100%; max-width:2000px; margin:auto; overflow:hidden; border-radius:18px; box-shadow:0 6px 18px rgba(0,0,0,0.2);">
  <div class="slider">
    {''.join([f'<img src="data:image/jpg;base64,{img}" class="slide">' for img in encoded_images])}
  </div>
</div>

<style>
.slider {{
  display: flex;
  width: {len(encoded_images) * 100}%;
  height: 360px;
  animation: slideAnimation {len(encoded_images) * 4}s infinite;
  border-radius: 18px;
}}

.slide {{
  width: {100 / len(encoded_images)}%;
  height: 360px;
  object-fit: cover;
  object-position: center center;
  flex-shrink: 0;
  border-radius: 18px;
}}

@keyframes slideAnimation {{
  {slider_keyframes}
}}
</style>
"""

    components.html(slider_html, height=365)
else:
    st.info("Hero slide images are missing. Add images named hero1.jpg to hero6.jpg inside the images folder.")

st.markdown("### AI-Based Analysis of Lung CT Scans")
st.write("Upload a CT scan image to receive a class prediction, visual explanations, and patient support guidance.")


# Image preprocessing
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

# Get class order directly from training dataset
dataset = datasets.ImageFolder("dataset/train")
classes = dataset.classes

# Load trained model
model = models.resnet18(pretrained=False)
model.fc = nn.Linear(model.fc.in_features, 2)
model.load_state_dict(torch.load("models/best_lung_cancer_model.pth", map_location="cpu"))
model.eval()

# Grad-CAM setup
target_layers = [model.layer4[-1]]
cam = GradCAM(model=model, target_layers=target_layers)

# Upload image
uploaded_file = st.file_uploader("Upload a CT scan image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded CT Scan", use_container_width=True)

    # Check if the uploaded image is likely a CT scan
    if not is_likely_ct_scan(image):
        st.error("Invalid image. Please upload a valid CT scan image.")
        st.stop()

    # Segmentation
    lung_mask = segment_lung(image)

    # Prepare image for model
    img = transform(image).unsqueeze(0)

    # Model prediction
    with torch.no_grad():
        outputs = model(img)
        probabilities = torch.softmax(outputs, dim=1)
        confidence, predicted = torch.max(probabilities, 1)

    prediction = classes[predicted.item()]
    confidence_score = confidence.item() * 100
    confidence_score = min(confidence_score, 99.5)

    # Show prediction
    st.write(f"### Prediction: {prediction}")
    st.write(f"### Confidence Score: {confidence_score:.2f}%")

    # Confidence category for the school-project report
    if prediction == "cancer":
        if confidence_score > 85:
            confidence_category = "High model confidence"
        else:
            confidence_category = "Moderate model confidence"

        st.write(f"### Confidence Category: {confidence_category}")
    else:
        confidence_category = "Not applicable"
        st.success("No cancer detected")

    # Medical disclaimer
    st.info("⚠️ This system is for educational purposes only and should not be used for medical diagnosis.")

    # Show an illustrative suspicious region only if cancer is predicted.
    # This is a demo overlay, not a separate object-detection model.
    if prediction == "cancer":
        img_with_boxes = np.array(image).copy()
        h, w, _ = img_with_boxes.shape

        x1 = int(w * 0.30)
        y1 = int(h * 0.25)
        x2 = int(w * 0.70)
        y2 = int(h * 0.65)

        cv2.rectangle(img_with_boxes, (x1, y1), (x2, y2), (0, 255, 0), 2)

        st.image(img_with_boxes, caption="Illustrative Suspicious Region (Demo)", use_container_width=True)
        st.caption("The green box is an illustrative region for presentation purposes. The Grad-CAM heatmap shows the model attention.")
    else:
        st.info("No illustrative suspicious region displayed because the scan was predicted as no cancer.")

    # Show segmentation
    st.image(lung_mask, caption="Segmented Lung Region", use_container_width=True)

    # Grad-CAM heatmap
    grayscale_cam = cam(input_tensor=img)[0]
    image_np = np.array(image.resize((224, 224))) / 255.0

    visualization = show_cam_on_image(
        image_np.astype(np.float32),
        grayscale_cam,
        use_rgb=True
    )

    st.image(visualization, caption="AI Attention Heatmap", use_container_width=True)

    # Create PDF Report
    pdf_path = create_pdf_report(
        prediction,
        confidence_score,
        confidence_category,
        lung_mask,
        visualization
    )

    with open(pdf_path, "rb") as pdf_file:
        st.download_button(
            label="📄 Download Medical PDF Report",
            data=pdf_file,
            file_name="lung_cancer_report.pdf",
            mime="application/pdf"
        )


st.subheader("Patient Support AI Chatbot")

user_input = st.text_input(
    "Ask about the prediction, confidence score, confidence category, heatmap, segmentation, symptoms, risk factors, or next steps:"
)

if user_input:
    question = user_input.lower().strip()

    current_prediction = prediction if "prediction" in locals() else "unknown"
    current_confidence = confidence_score if "confidence_score" in locals() else 0
    current_confidence_category = confidence_category if "confidence_category" in locals() else "Not available"

    response = ""

    # Greeting
    if question in ["hi", "hello", "hey"]:
        response = (
            "Hello. I can help explain the result, confidence score, confidence category, symptoms, risk factors, "
            "treatment basics, and what to do next."
        )

    # Result meaning
    elif "result" in question and ("mean" in question or "explain" in question):
        if current_prediction == "cancer":
            response = (
                f"The system predicts cancer with a confidence score of {current_confidence:.2f}%. "
                f"The confidence category is {current_confidence_category}. This means the model detected patterns similar to cancer cases, "
                "but this is not a final diagnosis and must be confirmed by a doctor."
            )
        elif current_prediction == "no_cancer":
            response = (
                f"The system predicts no cancer with a confidence score of {current_confidence:.2f}%. "
                "This means the model did not detect strong cancer-like patterns in the scan, "
                "but medical confirmation is still recommended."
            )
        else:
            response = "Please upload a CT scan first so I can explain the result."

    # Next step
    elif "next" in question or "what should i do" in question or "what do i do now" in question:
        if current_prediction == "cancer":
            response = (
                "The next step is to consult a qualified doctor or radiologist as soon as possible for proper evaluation, "
                "possible biopsy, and additional clinical tests."
            )
        elif current_prediction == "no_cancer":
            response = (
                "Even though the result is no cancer, you should still consult a doctor if symptoms continue or if the scan "
                "needs medical review."
            )
        else:
            response = "Please upload a CT scan first so I can guide you."

    # Trust / reliability
    elif "trust" in question or "reliable" in question or "accurate" in question:
        response = (
            "This system is designed to support analysis, but it is not a final medical authority. "
            "Its output should always be reviewed by a qualified healthcare professional."
        )

    # Confidence
    elif "confidence" in question:
        response = (
            f"The confidence score is {current_confidence:.2f}%. "
            "This shows how strongly the model supports its prediction, but it is not the same as a confirmed diagnosis."
        )

    # Confidence category / stage wording
    elif "confidence category" in question or "category" in question or "stage" in question:
        if current_prediction == "cancer":
            response = (
                f"The confidence category is {current_confidence_category}. This is based on the model score only, "
                "not on clinical cancer staging."
            )
        else:
            response = "No confidence category is shown because the current prediction is no cancer."

    # Symptoms
    elif "symptom" in question or "sign" in question:
        response = (
            "Common symptoms of lung cancer may include persistent cough, chest pain, coughing up blood, shortness of breath, "
            "unexplained weight loss, and fatigue. However, symptoms vary and only a doctor can evaluate them properly."
        )

    # Risk factors
    elif "risk" in question or "cause" in question:
        response = (
            "Common risk factors include smoking, secondhand smoke, family history, air pollution, and exposure to harmful substances "
            "such as asbestos. A doctor can help assess individual risk."
        )

    # Smoking
    elif "smoking" in question or "smoker" in question:
        response = (
            "Smoking is one of the biggest risk factors for lung cancer. However, non-smokers can also develop lung cancer, "
            "so medical evaluation is still important when symptoms or suspicious scans are present."
        )

    # Family history
    elif "family history" in question or "genetic" in question or "hereditary" in question:
        response = (
            "Family history can increase the risk of lung cancer, although it does not guarantee that someone will develop it. "
            "Doctors use family and medical history together when evaluating risk."
        )

    # Prevention
    elif "prevent" in question or "prevention" in question:
        response = (
            "Risk may be reduced by avoiding smoking, reducing exposure to harmful substances, maintaining regular medical checkups, "
            "and seeking evaluation early when symptoms appear."
        )

    # Early detection
    elif "early detection" in question or "detect early" in question:
        response = (
            "Early detection is important because treatment is often more effective when lung cancer is found at an earlier stage."
        )

    # Treatment
    elif "treatment" in question or "treat" in question or "therapy" in question:
        response = (
            "Treatment may include surgery, chemotherapy, radiation therapy, targeted therapy, or immunotherapy depending on medical "
            "evaluation. A doctor must decide the appropriate treatment plan."
        )

    # Biopsy
    elif "biopsy" in question:
        response = (
            "A biopsy is a medical procedure used to collect tissue so doctors can confirm whether cancer cells are present. "
            "It is often important for final diagnosis."
        )

    # CT scan meaning
    elif "ct scan" in question or "scan" in question:
        response = (
            "A CT scan creates detailed cross-sectional images of the body and helps doctors examine lung structure and possible abnormalities."
        )

    # Heatmap
    elif "heatmap" in question or "why did the model focus" in question:
        response = (
            "The heatmap shows the region of the scan that influenced the AI model most strongly when making its prediction."
        )

    # Segmentation
    elif "segmentation" in question or "lung region" in question:
        response = (
            "Segmentation isolates the lung area so the system can focus on the most relevant part of the CT scan."
        )

    # False positives / false alarm
    elif "false positive" in question or "false alarm" in question:
        response = (
            "A false positive means the system flagged cancer when no cancer is actually present. "
            "This is why doctor confirmation is always necessary."
        )

    # Hospital use
    elif "hospital" in question or "clinic" in question or "real world" in question:
        response = (
            "This system is an educational support tool and is not yet intended for direct clinical deployment without further validation."
        )

    # Doctor / diagnosis
    elif "doctor" in question or "diagnosis" in question:
        response = (
            "A doctor should always make the final diagnosis. This system is meant to support analysis, not replace professional medical judgment."
        )

    # Safety / disclaimer
    elif "safe" in question or "disclaimer" in question:
        response = (
            "This system is for educational purposes only and should not be used as a final medical diagnosis. "
            "Always consult a qualified healthcare professional."
        )

    # Emotional support
    elif "worried" in question or "scared" in question or "afraid" in question:
        response = (
            "It is understandable to feel worried. The best next step is to speak with a qualified doctor who can evaluate the scan properly "
            "and guide you through the next steps."
        )

    # Normal / no cancer
    elif "normal" in question or "no cancer" in question:
        if current_prediction == "no_cancer":
            response = (
                "The system predicted no cancer, which means no strong cancer-related pattern was detected in the scan."
            )
        else:
            response = (
                "The current result is not no cancer. The model detected suspicious patterns, so professional medical review is recommended."
            )

    # Fallback
    else:
        response = (
            "I can help explain the result, confidence score, confidence category, symptoms, risk factors, prevention, treatment basics, "
            "CT scan meaning, and what to do next."
        )

    st.markdown("###  Chatbot Response")
    st.success(response)
